services:

    launcher:
        build:
            context: launcher
        restart: always
        stdin_open: true
        tty: true
        volumes:
        - launcher:/app/data

    nginx:
        build:
            context: nginx
        restart: always
        volumes:
            - launcher:/volume
        ports:
            - 17549:80
        depends_on:
            - launcher

#    database:
#        image: "postgres:17.0-alpine3.20"
#        container_name: database
#        ports:
#            - "5432:5432"
#        environment:
#            - POSTGRES_USER=postgres
#            - POSTGRES_PASSWORD=password
#        volumes:
#            - postgres-data:/var/lib/postgresql/data

#    application:
#        image: "cunningbird/demo:1.0.0"
#        container_name: application
#        build:
#            context: .
#            args:
#                publicDependenciesRepositoryUrl: https://repo.maven.apache.org/maven2/
#                publicPluginsRepositoryUrl: https://plugins.gradle.org/m2/
#        ports:
#            - "8080:8080"
#        environment:
#            - SPRING_APPLICATION_PORT=8080
volumes:
    launcher:
    postgres-data: